version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
